### ISSUE TITLE
FriendlyId History Support

### ISSUE THREAD

**Issue by halilim** [norman/friendly_id-globalize#13]
It looks like [FriendlyId's `:history`](http://norman.github.io/friendly_id/file.Guide.html#History__Avoiding_404_s_When_Slugs_Change) option isn't supported. Would it be hard to implement? And any workaround would be valuable, thanks.

**Comment by sasselin** [comment]
+1

**Comment by sasselin** [comment]
https://github.com/norman/friendly_id-globalize/pull/14
