### ISSUE TITLE
[attr]_changed? always nil in "should_generate_new_friendly_id?" method

### ISSUE THREAD

**Issue by anthony-robin** [norman/friendly_id-globalize#17]
I am using `friendly_id` and `friendly_id-globalize` gems in my Rails project. 

Every time I update an article, the method `title_changed?` is always nil even if I change it in the form which make slug never being updated. 
It might be a gem bug.

For more details, I opened a [StackOverflow post](http://stackoverflow.com/questions/40102665/friendlyid-doesnt-update-slug-on-title-changed).

**Comment by n-rodriguez** [comment]
Did you try `attribute_changed?('title')`?
