### ISSUE TITLE
Add to README - Config order is important

### ISSUE THREAD

**Issue by lenart** [norman/friendly_id-globalize#8]
I've just tried to use `friendly_id-globalize` with `globalize` 4.0.3 (rails-4-2 branch) and got an error because FriendlyId config was called before `translates`. Even running something as simple as `BlogPost.first` raised an error

```ruby
[1] pry(main)> BlogPost.first
NoMethodError: undefined method `translated_attribute_names' for BlogPost (call 'BlogPost.connection' to establish a connection):Class
from /Users/lenart/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
``` 

Adding this to the readme might save someone else the frustration of figuring this out on their own.

If it's easier for you I can prepare the pull request.

**Comment by lenart** [comment]
Just found a related issue https://github.com/globalize/globalize/issues/157

**Comment by parndt** [comment]
Is this an issue with Globalize 5.0.0?

**Comment by lenart** [comment]
I had this problem with globalize 4.0.3.
```
  remote: git://github.com/globalize/globalize.git
  revision: 1d8202a83fea23f39e8f7567c3030050847a9629
  branch: rails-4-2-upgrade
```
 Not sure about 5.0.0 because I couldn't get it to work with other gems.

**Comment by parndt** [comment]
Which other gems?

**Comment by lenart** [comment]
@parndt there's a problem with `globalize-versioning` gemspec.

```
Bundler could not find compatible versions for gem "globalize":
  In Gemfile:
    globalize-versioning (>= 0) ruby depends on
      globalize (< 5, >= 3) ruby

    globalize (5.0.0)
```

**Comment by parndt** [comment]
I believe globalize-versioning was updated to 0.1.0; is the problem still present?

**Comment by lenart** [comment]
I've created a blank project with single model and had no errors when using

```ruby
friendly_id (5.1.0)
friendly_id-globalize (1.0.0.alpha1)
globalize (5.0.1)
globalize-versioning (0.1.0)
paper_trail (3.0.7)
```

Note that `translates` should be called before `friendly_id`. I still believe this **should be added to the README file**.

Here's the model for reference:

```ruby
class Post < ActiveRecord::Base
  translates :title, :body, :slug, versioning: :paper_trail

  extend FriendlyId
  friendly_id :title, use: [:slugged, :globalize]

  has_paper_trail
end
```

**Comment by parndt** [comment]
Can you please add it for us?

**Comment by lenart** [comment]
Done https://github.com/norman/friendly_id-globalize/pull/11
